### ISSUE TITLE
Set +q $~a on #ruby permanently

### ISSUE THREAD

**Issue by radar** [apeiros/ruby-community#19]
I am proposing today that we set `+q $~a` on #ruby permanently. This mode stops unregistered users from talking in the channel, but they may still join. We can specify in the topic that users must be registered before they talk _and_ we could setup the bot to message unauthenticated users to authenticate before talking in the channel.

We have this mode set on #rubyonrails because we were getting spammers who kept coming into the channel. Since this mode has been set, we don't get these spammers any more.

I'd like to open a discussion about having this mode set permanently on the #ruby channel.

**Comment by apeiros** [comment]
Please give your rationale and state "pro +q" or "contra +q" at the end. We consider votes given until Sunday 31st of may, 12.00 UTC.

[Update 2 - new ops from #ruby-lang] Current status:
Pro +q:
- @sevenseacat 
- @miah
- @CoralineAda

Contra +q:
- @jhass
- @apeiros
- @Mon-Ouie
- @havenwood
- @banister
- @zenspider
- @leejarvis (ljarvis)
- @aredridel (Aria)
- @radar
- @zzak
- @drbrain
- @djberg96 (imperator)

Abstention:
- @workmad3

Pro: 3, Contra: 12, Abstentions: 1, Pending: 3
Pending: @seanstickle, slyphon, and fflush.
No longer op: @sepp2k (on his own wish)
I could not reach from those: slyphon, fflush. I tried until sunday evening. I will not try anymore.

**Comment by sevenseacat** [comment]
I thought jhass already asked everyone about this? They asked me, anyway.

It will keep out the idiotic spammer that has decided to focus on abusing me, and other dumb spammers, so +1 from me.

(edit) the other alternative I wouldn't mind would be a blanket ban on users coming in via the webchat. That's where they all seem to come from.

<b>pro +q</b>

**Comment by apeiros** [comment]
@sevenseacat yes, jhass asked as many as he could reach. @radar wishes for a paper trail. That's IMO a good idea and until we've better tools, using github issues is an acceptable way.

**Comment by miah** [comment]
I've seen the spammer issue in a few channels and this mode has been helpful.

It also prevents people from changing nick to avoid a weak ban or to harass.

pro +q

**Comment by jhass** [comment]
Currently #ruby is the best place for people new to the language to get information and help with it. Having to register raises the barrier of entry significantly. The operator job is it to make it easy for the user, not easy for the operator.

**contra +q**

**Comment by apeiros** [comment]
My opinion on this
- pro +q: higher barrier for offenders.
- contra +q: higher barrier for newbies. A dedicated offender is not stopped by +q.

Tools to help with the contras:
- Prefix the channel topic with "Register to talk || "
- Prefix welcome message with "Register to talk || "
- Set +z on the channel, so unregistered and helpless users can talk to channel ops
- Let ruboto actively inform first-time joiners who are not registered

Since +z would only message currently opped users, and permanently opping is
considered bad practice, we could perma-op ruboto and let it stream unauthed
user messages to ops and/or #ruby-banned/#ruby-ops. This also gives us insight
in how much (or little) trouble is generated by +q, which enables us to make
informed decisions in the future.

I suggest that if we decide to use +q, we also discuss those measures in a
separate issue.

I'm in favor of use +q as a temporary measure. But I'm currently against using
it as a permanent measure. With the above support measures, I could change my
opinion. But for now:

**contra +q**

**Comment by Mon-Ouie** [comment]
I'm also against this because I've already seen people join #ruby rather than #ruby-lang because they couldn't join the latter, not to mention the deterring effect it would have on people who don't use IRC on a regular basis and just joined to ask a question.

Having+q makes it harder for spammers and people trying to circumvent bans, which does happen, but not often enough to warrant that measure in my opinion.

**contra +q**

**Comment by CoralineAda** [comment]
I'm in favor of +q. Spammers and offenders are, in my limited experience, incredibly detrimental to the community-building efforts around the channel. Regardless of the frequency of these incidents, they are bad enough to create a very negative impression of the overall channel, especially for newbies. 

pro +q

**Comment by havenwood** [comment]
I worry that a blanket +q takes voice away from new folk who need help the most. If it’s possible to effectively repel the trolls without silencing newcomers that seems worth trying for.

I'm in favor of temporary +q and other measures as needed to stop harassment. But it doesn't seem friendly to not allow newcomers to speak at all. At this point at least I'd still like to explore alternatives to a permanent silence.

contra +q

**Comment by banister** [comment]
helping new folk > the need to fight against spamming. If spamming is a significant problem (I don't even think it is in #ruby) then we just need more ops spanning multiple timezones to regulate the channel better. 

**contra +q**

**Comment by zenspider** [comment]
The thing is, spammers often come in waves. Looking at the current banlist, the latest several entries are:

```
swastika!*@*                                       ChanServ!ChanServ@services.
ARYAN_NATIONS!*@*                                  ChanServ!ChanServ@services.
KKKLANSMAN!*@*                                     apeiros!~apeiros@apeiros.me
der_fuhrer!*@*                          miah!~miah@archserver/trusteduser/miah
```

If, during these waves, we could have stricter policy it would make things more adaptable. Either institute the **+q** ban temporarily (30-60 minutes at a time?) until the individual(s) gets bored and moves on or have some sort of auto-mute we can automated via bot. Something...

That said, I'm basically saying I'm **pro +q** except that my main focus in being in there is to help newbs so in that sense I'm **contra +q**. I'm sure there are other alternatives in IRC-land. I'm not the most experienced op.

Overall, I value signal:noise more than I value overly-free-to-the-point-of-harrassment speech, so I guess I'll throw in:

<strike>**pro +q** (with caveats)</strike>

**contra +q** since we're talking about anything _"permanent"_

**Comment by zenspider** [comment]
```
<jhass> zenspider: well, I read you'd like temporary +q $~a (which I would
        agree to actually), but this vote is about a permanent measure  [02:39]
...
<zenspider> jhass: if we're talking permanent, and there's no easy way to
            automatically teach newbs the hoops they have to jump through,
            then I guess I'd vote against.
```

**Comment by leejarvis** [comment]
> Either institute the +q ban temporarily (30-60 minutes at a time?) until the individual(s) gets bored and moves on or have some sort of auto-mute we can automated via bot

I think this would be a good idea. I agree that +q is quite detrimental for newbies and we should try and avoid increasing the difficulty of them being helped. Many of the ops in #ruby are online and moderating the channel around the clock (and now there are more from #ruby-lang) so spam gets picked up quite quickly. 

**contra +q**

**Comment by radar** [comment]
I had no idea that the #ruby and #ruby-lang channels would be merging. I now think that we have enough  ops to cover most (if not all) timezones and so my opinion has switched to being **contra permanent +q**. We have the tools and access to the bot to quiet users and we can react using those.

Very glad we've merged the two groups together! Well done to all involved. :tada:

**Comment by aredridel** [comment]
contra, but pro using it temporarily.

**contra +q**

**Comment by djberg96** [comment]
I think with the merging of #ruby and #ruby-lang we should have good operations coverage so a permanent +q isn't necessary.

contra +q

**Comment by workmad3** [comment]
I don't have strong feelings either way, so I'm happy for whichever majority wins out (currently looks like **contra** :smile: )

**Comment by zzak** [comment]
I'm also :-1: to this, registration will only make it more difficult for beginners.

**Comment by drbrain** [comment]
Contra +q since it is a barrier for new ops.

**Comment by radar** [comment]
Given the spate of recent spam, I would like to take new votes on having this mode added permanently.

**Comment by sevenseacat** [comment]
> [15:05:23] sevenseacat:   to be honest I would be a bit upset if (spam + op abuse) doesnt warrant a +q, but (spam alone) does

**Comment by baweaver** [comment]
Torn myself.

_Pro logic_

Incessant spam, kiwiirc, and other such things end up diving the channel into debates of why someone got kicked (if it happened elsewhere) and other meta topics. The entire `?guys` fiasco has ended up lighting some interesting corners of the channel unfortunately as well.

While it can be difficult for new users to get on from this, a simple getting started should suffice in most all cases. SASL is a very easy option to enable on any modern client.

_Contra_

Even that barrier scares people off potentially, and honestly the worst these people can do are a few minutes of annoyance every few hours. With good ops coverage it rarely becomes a large issue.

---

Overall I'd lean _pro_, the key factor for me is that the barrier is far more annoying to trolls than it is to people legitimately wanting help.

**Comment by CoralineAda** [comment]
Registering a nick is a pretty low bar, and if you're going to IRC anyway then it's already a good idea to just do it. I don't think IRC is the first choice for people looking for help so I doubt that there's a general sense of urgency with getting on for the first time and getting a question answered.

And if it reduces the amount of crap people we have drifting in, letting ops do more question answering and community tending, all the better.

Pro.

**Comment by omninonsense** [comment]
I think most people who come seeking help are IRC tourists, not locals. Is there a way to verify this, though? 

:-1: Spam is annoying, but we shouldn't allow spam to create collateral damage (and prevent people from seeking help).

**Comment by jhass** [comment]
I don't think anything changed, temporary +q $~a is a fine and working measure, permanent +q $~a is just avoiding responsibilities you take by accepting to be an op.

Overall my arguments and thus my vote stay the same as above, please don't be annoying and reopen the vote every of couple of months because you don't like its outcome.

-1 / Contra / :-1: / whatever

**Comment by banister** [comment]
Agree with @jhass and about temporary +q i'm also :-1: (contra)

**Comment by workmad3** [comment]
I agree with @jhass that nothing has changed, apart from everyone having a fresh example of troll behaviour in their minds as opposed to the possibility of it when this was last discussed. No new scenarios have come up, so I vote that the original :-1: contra vote should stand.

**Comment by aredridel** [comment]
What about the responsibility of being an op requires `-q`? That's never been a rule. What responsibility are you talking about?

**Comment by jhass** [comment]
The responsibility of watching the channel and taking action on specific malicious users. `+q $~a` is just reducing that workload on the cost of excluding a significant amount of valid users.

**Comment by aredridel** [comment]
You've a narrow and specific view of what ops do!

But how significant are we talking here? Got numbers?

**Comment by jhass** [comment]
It's hard to measure users you can't see talking. From my feeling it's 5-6 questions less per day with `+q $~a` on.

**Comment by aredridel** [comment]
To make a less hostile environment that sounds quite pleasant.

**Comment by apeiros** [comment]
If we vote about it again, please use a new issue (or if we should have it by then - the voting system)
